# Generated by Django 5.2 on 2025-04-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
