# Generated by Django 5.2 on 2025-04-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_model_is_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="api_environment_variable",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="model",
            name="base_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
