# Generated by Django 5.2 on 2025-04-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_model_api_environment_variable_model_base_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="is_openai",
            field=models.BooleanField(default=False),
        ),
    ]
