# Generated by Django 5.2 on 2025-04-12 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_model_is_openai"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="chat.model",
            ),
        ),
    ]
