# Generated by Django 5.2 on 2025-04-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_thread_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("openai", "Openai"),
                    ("huggingface", "Huggingface"),
                    ("gemini", "Gemini"),
                ],
                default="openai",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
