# Generated by Django 5.2 on 2025-04-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_model_model_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="is_online",
        ),
        migrations.RemoveField(
            model_name="model",
            name="is_openai",
        ),
        migrations.AlterField(
            model_name="model",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("openai", "Openai"),
                    ("huggingface", "Huggingface"),
                    ("gemini", "Gemini"),
                    ("local", "Local"),
                ],
                max_length=255,
            ),
        ),
    ]
