# Generated by Django 5.2 on 2025-04-17 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_remove_model_is_online_remove_model_is_openai_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="model",
            name="model_type",
        ),
        migrations.AddField(
            model_name="model",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="chat.modeltype",
            ),
        ),
    ]
