# Generated by Django 5.2 on 2025-04-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_alter_model_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="temperature",
            field=models.FloatField(default=0.7),
        ),
    ]
