# Generated by Django 5.2 on 2025-04-18 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_model_temperature"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="identifier",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="model",
            name="temperature",
            field=models.FloatField(
                default=0.7,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
