# Generated by Django 5.2 on 2025-04-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_model_identifier_alter_model_temperature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
