# Generated by Django 5.2 on 2025-04-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_alter_model_identifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model",
            name="base_url",
        ),
    ]
