# Generated by Django 5.2 on 2025-04-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_remove_model_base_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="model",
            old_name="type",
            new_name="provider",
        ),
    ]
